version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: Qwer1234!   # 设置数据库密码
      POSTGRES_USER: gyfrank                 # 设置数据库用户名
      POSTGRES_DB: 7403_assignment_database               # 设置数据库名称
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # 挂载初始化脚本到容器内
    networks:
      - my_network
    ports:
      - "5432:5432"  # 映射端口

  server:
    build: ./server
    container_name: server
    networks:
      - my_network
    ports:
      - "3000:3000"
    depends_on:
      - postgres  # 确保 PostgreSQL 在 Node 应用之前启动

  nginx:
    build: ./web
    container_name: nginx
    networks:
      - my_network
    ports:
      - "6110:6110"
      - "6111:6111"
    volumes:
      - ./web/6110_vote_page:/usr/share/nginx/html/vote
      - ./web/6111_results_page:/usr/share/nginx/html/results
      - ./web/nginx.conf:/etc/nginx/nginx.conf

networks:
  my_network:
    driver: bridge
